### PR TITLE
Fix ecs

### PR DESCRIPTION
**Pull request by szepeviktor**
CI has not caught this.
How could this happen?

What do you think?

This is the diff of CI vs. my local machine with PHP 7.4
https://gist.github.com/szepeviktor/fc087d541ccb9c12416e5972ca6ffaab/revisions

### CODE REVIEW

**Comment by loevgaard** [comment]
Where is the syntax error in this PR?

**Comment by szepeviktor** [comment]
I've tried inventing a syntax error then I've ran into this ecs issue.

Somehow CI installs older packages!
See the diff: https://gist.github.com/szepeviktor/fc087d541ccb9c12416e5972ca6ffaab/revisions

**Comment by szepeviktor** [comment]
Latest `sylius-labs/coding-standard` needs PHP 8.0!
So it is not installed on PHP 7.4.

Why is it installed on my computer??

**Comment by szepeviktor** [comment]
It turns out my composer command is hijacked to always run on PHP 8.0 😲

**Pull request closed without merging**
